modules:
  - tasks/controllers.py
  - tasks/de_evaluators.py
  - tasks/de_initialisers.py
  - tasks/de_selectors.py
  - tasks/replacers.py
  - tasks/mutators.py
  - tasks/crossover.py
  - tasks/loggers.py
pipelines:
  - name: DeJongOnePipeline
    controller:
      name: GenerationController
      params:
        - 1000
    initialisers:
      - name: DeJongOneInitialiser
        params:
          - [100, 50]
    tasks:
      - name: RandomSelector
      - name: DifferenceSelector
        params:
          - [2]
      - name: CrossoverSelectorEach
      - name: DeMutator
        params:
          - 0.3
      - name: BinomialCrossover
        params:
          - 0.5
      - name: DeParentAllocatorCrossover
      - name: DeJongOneEvaluator
      - name: BetterReplacer
      - name: TerminalLogger
    finalisers: []
