modules:
  - tasks/controllers.py
  - tasks/de_evaluators.py
  - tasks/de_initialisers.py
  - tasks/de_selectors.py
  - tasks/replacers.py
  - tasks/mutators.py
  - tasks/crossover.py
  - tasks/loggers.py
  - tasks/finalisers.py
runs: 10
pipelines:
  - name: DeJongOnePipeline_DE
    controller:
      name: GenerationController
      params:
        - 10000
    initialisers:
      - name: DeJongOneInitialiser
        params:
          - [50, 20]
    tasks:
      - name: RandomSelector
      - name: DifferenceSelectorAncestor
        params:
          - [1, 0.1]
          - [1, 0.2]
          - [1, 0.3]
          - [1, 0.4]
          - [1, 0.5]
      - name: CrossoverSelectorEach
      - name: DeMutator
        params:
          - 0.1
          - 0.2
          - 0.3
          - 0.4
          - 0.5
      - name: BinomialCrossover
        params:
          - 0.1
          - 0.2
          - 0.3
          - 0.4
          - 0.5
      - name: DeParentAllocatorCrossover
      - name: DeJongOneEvaluator
      - name: BetterReplacer
      - name: PercentRemainingLogger
    finalisers:
      - name: DescriptionBuilder
      - name: ResultsBuilder
      - name: MongoDbSaver
        params:
          - ["ga_user", "ga_user", "ga", "de_results", "lifenoodles.com", "27018"]

  - name: DeJongOnePipeline
    controller:
      name: GenerationController
      params:
        - 10000
    initialisers:
      - name: DeJongOneInitialiser
        params:
          - [50, 20]
    tasks:
      - name: RandomSelector
      - name: DifferenceSelector
        params:
          - 1
      - name: CrossoverSelectorEach
      - name: DeMutator
        params:
          - 0.1
          - 0.2
          - 0.3
          - 0.4
          - 0.5
      - name: BinomialCrossover
        params:
          - 0.1
          - 0.2
          - 0.3
          - 0.4
          - 0.5
      - name: DeParentAllocatorCrossover
      - name: DeJongOneEvaluator
      - name: BetterReplacer
      - name: PercentRemainingLogger
    finalisers:
      - name: DescriptionBuilder
      - name: ResultsBuilder
      - name: MongoDbSaver
        params:
          - ["ga_user", "ga_user", "ga", "de_results", "lifenoodles.com", "27018"]
