modules:
  - tasks/controllers.py
  - tasks/de_evaluators.py
  - tasks/de_initialisers.py
  - tasks/de_selectors.py
  - tasks/replacers.py
  - tasks/mutators.py
  - tasks/crossover.py
  - tasks/loggers.py
  - tasks/finalisers.py
runs: 1
pipelines:
  - name: DeJongOnePipeline
    controller:
      name: GenerationController
      params:
        - 10000
    initialisers:
      - name: RastriginSixInitialiser
        params:
          - [20, 10]
    tasks:
      - name: RandomSelector
      - name: DifferenceSelector
        params:
          - [1]
      - name: CrossoverSelectorEach
      - name: DeMutator
        params:
          - 0.8
      - name: BinomialCrossover
        params:
          - 0.5
      - name: RastriginSixEvaluator
      - name: DeParentAllocatorCrossover
      - name: BetterReplacer
      - name: TerminalLogger
    finalisers:
      - name: DescriptionBuilder
      - name: ResultsBuilder
