modules:
  - tasks/controllers.py
  - tasks/de_evaluators.py
  - tasks/de_initialisers.py
  - tasks/de_selectors.py
  - tasks/replacers.py
  - tasks/mutators.py
  - tasks/crossover.py
  - tasks/loggers.py
  - tasks/finalisers.py
  - tasks/constrainers.py
runs: 1
pipelines:
  - name: DeJongOnePipeline
    controller:
      name: GenerationController
      params:
        - 1000
    initialisers:
      - name: DeJongThreeInitialiser
        params:
          - [10, 5]
    tasks:
      - name: RandomSelector
      - name: DifferenceSelectorAncestor
        params:
          - [1, 1]
      - name: CrossoverSelectorEach
      - name: DeMutator
        params:
          - 0.5
      - name: ExponentialCrossover
        params:
          - 0.5
      - name: BoundsConstrainer
      - name: DeJongThreeEvaluator
      - name: DeParentAllocatorCrossover
      - name: BetterReplacer
      - name: TerminalLogger
    finalisers:
      - name: DescriptionBuilder
      - name: ResultsBuilder
